site_name: Uncertainty playground

theme:
  name: "material"
  features:
    - content.code.copy
    - content.code.select
  font: 
      text: Fira Sans
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      accent:  deep orange
      scheme: default
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent:  purple
      scheme: slate
      toggle:
        icon: material/brightness-6
        name: Switch to light mode

repo_name: Unco3892/UncertaintyPlayground
repo_url: https://github.com/Unco3892/UncertaintyPlayground/

plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [uncertaintyplayground]

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Code Reference: reference/
  - About: index.md
  - Usage: usage.md
  - Bibliography: bib.md